/**
 * Trade note template.
 * Renders a per-trade markdown note for the Obsidian vault.
 */

export interface TradeNoteContext {
  position: {
    id: string;
    symbol: string;
    direction: string;
    openPrice: number;
    closePrice: number;
    stopLoss: number;
    takeProfit: number;
    volumeLots: number;
    openedAt: string;
    closedAt: string;
    durationMinutes: number;
    realizedPnl: number;
    realizedPnlPct: number;
    strategy: string | null;
    closeReason: string | null;
    account: string;
    phase: string;
  };
  preTradeReview: {
    verdict: string;
    summary: string;
    concerns: string[];
    suggestions: string[];
  } | null;
  postTradeReview: {
    summary: string;
    whatWentWell: string[];
    whatWentPoorly: string[];
    lessons: Array<{ title: string; detail: string; tags: string[] }>;
    nextSetupsToWatch: string[];
  } | null;
  validation: {
    winRatePct: number;
    expectancy: number;
    sampleSize: number;
    finalScore: number;
  } | null;
}

export const renderTradeNote = (ctx: TradeNoteContext, generatedAt: string): string => {
  const { position: p } = ctx;
  const pnlSign = p.realizedPnl >= 0 ? "+" : "";
  const outcome = p.realizedPnl >= 0 ? "WIN" : "LOSS";
  const pnlPctSign = p.realizedPnlPct >= 0 ? "+" : "";

  const lines: string[] = [
    `---`,
    `title: "${p.symbol} ${p.direction} ${outcome}"`,
    `date: ${p.closedAt.split("T")[0]}`,
    `symbol: ${p.symbol}`,
    `direction: ${p.direction}`,
    `outcome: ${outcome}`,
    `pnl: ${pnlSign}${p.realizedPnl.toFixed(2)}`,
    `pnlPct: ${pnlPctSign}${p.realizedPnlPct.toFixed(2)}`,
    `account: ${p.account}`,
    `phase: ${p.phase}`,
    `strategy: ${p.strategy ?? "untagged"}`,
    `closeReason: ${p.closeReason ?? "unknown"}`,
    `tags: [trade, ${p.symbol.toLowerCase()}, ${p.direction.toLowerCase()}, ${outcome.toLowerCase()}]`,
    `---`,
    ``,
    `# ${p.symbol} ${p.direction} — ${pnlSign}${p.realizedPnl.toFixed(2)} USD (${pnlPctSign}${p.realizedPnlPct.toFixed(2)}%)`,
    ``,
    `## Trade Details`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Account | ${p.account} |`,
    `| Phase | ${p.phase} |`,
    `| Strategy | ${p.strategy ?? "—"} |`,
    `| Entry | ${p.openPrice.toFixed(5)} |`,
    `| Close | ${p.closePrice.toFixed(5)} |`,
    `| Stop | ${p.stopLoss.toFixed(5)} |`,
    `| Take Profit | ${p.takeProfit.toFixed(5)} |`,
    `| Size | ${p.volumeLots} lots |`,
    `| Opened | ${p.openedAt} |`,
    `| Closed | ${p.closedAt} |`,
    `| Duration | ${p.durationMinutes} min |`,
    `| Close Reason | ${p.closeReason ?? "—"} |`,
    ``,
  ];

  if (ctx.validation) {
    const v = ctx.validation;
    lines.push(
      `## Validation Metrics`,
      ``,
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Win Rate | ${v.winRatePct.toFixed(1)}% |`,
      `| Expectancy | ${v.expectancy.toFixed(3)} |`,
      `| Sample Size | ${v.sampleSize} |`,
      `| Final Score | ${v.finalScore.toFixed(1)} |`,
      ``,
    );
  }

  if (ctx.preTradeReview) {
    const r = ctx.preTradeReview;
    lines.push(
      `## Pre-Trade AI Review`,
      ``,
      `**Verdict:** \`${r.verdict}\`  `,
      `**Summary:** ${r.summary}`,
      ``,
    );
    if (r.concerns.length > 0) {
      lines.push(`**Concerns:**`);
      r.concerns.forEach((c) => lines.push(`- ${c}`));
      lines.push(``);
    }
    if (r.suggestions.length > 0) {
      lines.push(`**Suggestions:**`);
      r.suggestions.forEach((s) => lines.push(`- ${s}`));
      lines.push(``);
    }
  }

  if (ctx.postTradeReview) {
    const r = ctx.postTradeReview;
    lines.push(
      `## Post-Trade Debrief`,
      ``,
      r.summary,
      ``,
    );
    if (r.whatWentWell.length > 0) {
      lines.push(`### What Went Well`);
      r.whatWentWell.forEach((w) => lines.push(`- ${w}`));
      lines.push(``);
    }
    if (r.whatWentPoorly.length > 0) {
      lines.push(`### What Went Poorly`);
      r.whatWentPoorly.forEach((w) => lines.push(`- ${w}`));
      lines.push(``);
    }
    if (r.lessons.length > 0) {
      lines.push(`### Lessons`);
      r.lessons.forEach((l) => {
        lines.push(`**${l.title}**  `);
        lines.push(`${l.detail}`);
        if (l.tags.length > 0) lines.push(`Tags: ${l.tags.map((t) => `\`${t}\``).join(", ")}`);
        lines.push(``);
      });
    }
    if (r.nextSetupsToWatch.length > 0) {
      lines.push(`### Setups to Watch`);
      r.nextSetupsToWatch.forEach((s) => lines.push(`- ${s}`));
      lines.push(``);
    }
  }

  lines.push(`---`, `*Generated by StocksScalper on ${generatedAt}*`);
  return lines.join("\n");
};
