/**
 * Weekly review note template.
 */

export interface WeeklyNoteContext {
  account: string;
  weekStart: string;
  weekEnd: string;
  kpis: {
    totalTrades: number;
    wins: number;
    losses: number;
    winRatePct: number;
    totalPnl: number;
    totalPnlPct: number;
    avgRR: number;
    largestWin: number;
    largestLoss: number;
    maxDrawdownPct: number;
    tradesPerDay: number;
  };
  review: {
    summary: string;
    topWins: string[];
    topLosses: string[];
    repeatingMistakes: string[];
    setupsWorking: string[];
    setupsFailing: string[];
    ruleAdherenceNotes: string[];
    recommendations: string[];
  };
}

export const renderWeeklyNote = (ctx: WeeklyNoteContext, generatedAt: string): string => {
  const { kpis: k, review: r } = ctx;
  const pnlSign = k.totalPnl >= 0 ? "+" : "";
  const pnlPctSign = k.totalPnlPct >= 0 ? "+" : "";

  const lines = [
    `---`,
    `title: "Week ${ctx.weekStart} — ${ctx.account}"`,
    `account: ${ctx.account}`,
    `weekStart: ${ctx.weekStart}`,
    `weekEnd: ${ctx.weekEnd}`,
    `tags: [weekly-review, ${ctx.account.toLowerCase().replace(/\s+/g, "-")}]`,
    `---`,
    ``,
    `# Weekly Review — ${ctx.account} — ${ctx.weekStart}`,
    ``,
    `## Performance`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total Trades | ${k.totalTrades} |`,
    `| Wins / Losses | ${k.wins} / ${k.losses} |`,
    `| Win Rate | ${k.winRatePct.toFixed(1)}% |`,
    `| Total PnL | ${pnlSign}${k.totalPnl.toFixed(2)} USD (${pnlPctSign}${k.totalPnlPct.toFixed(2)}%) |`,
    `| Avg R:R | ${k.avgRR.toFixed(2)} |`,
    `| Largest Win | +${k.largestWin.toFixed(2)} |`,
    `| Largest Loss | ${k.largestLoss.toFixed(2)} |`,
    `| Max Drawdown | ${k.maxDrawdownPct.toFixed(2)}% |`,
    `| Trades/Day | ${k.tradesPerDay.toFixed(1)} |`,
    ``,
    `## Summary`,
    ``,
    r.summary,
    ``,
  ];

  if (r.topWins.length > 0) {
    lines.push(`## Top Wins`, ``);
    r.topWins.forEach((w) => lines.push(`- ${w}`));
    lines.push(``);
  }

  if (r.topLosses.length > 0) {
    lines.push(`## Top Losses`, ``);
    r.topLosses.forEach((l) => lines.push(`- ${l}`));
    lines.push(``);
  }

  if (r.repeatingMistakes.length > 0) {
    lines.push(`## Repeating Mistakes`, ``);
    r.repeatingMistakes.forEach((m) => lines.push(`- ${m}`));
    lines.push(``);
  }

  if (r.setupsWorking.length > 0) {
    lines.push(`## Setups Working`, ``);
    r.setupsWorking.forEach((s) => lines.push(`- ${s}`));
    lines.push(``);
  }

  if (r.setupsFailing.length > 0) {
    lines.push(`## Setups Failing`, ``);
    r.setupsFailing.forEach((s) => lines.push(`- ${s}`));
    lines.push(``);
  }

  if (r.ruleAdherenceNotes.length > 0) {
    lines.push(`## Rule Adherence`, ``);
    r.ruleAdherenceNotes.forEach((n) => lines.push(`- ${n}`));
    lines.push(``);
  }

  if (r.recommendations.length > 0) {
    lines.push(`## Next Week`, ``);
    r.recommendations.forEach((rec) => lines.push(`- ${rec}`));
    lines.push(``);
  }

  lines.push(`---`, `*Generated by StocksScalper on ${generatedAt}*`);
  return lines.join("\n");
};
