/**
 * Journal Export Sweeper Job
 *
 * Runs every ~5 minutes. Processes PENDING JournalExport rows by writing
 * markdown files to the Obsidian vault. This is the async tail of the
 * Obsidian export pipeline — all other jobs queue JournalExport rows
 * and this sweeper actually writes the files.
 *
 * Idempotent: if the content hash matches the existing file, no write occurs.
 * Atomic: writes to .tmp first, then renames. Never leaves partial files.
 */

import { prisma } from "@stock-radar/db";
import { createLogger } from "@stock-radar/logging";
import { writeFile, mkdir, rename, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join, resolve, normalize } from "node:path";
import { existsSync } from "node:fs";

const logger = createLogger("journal-export-sweeper");

const VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH ?? "";
const OBSIDIAN_ENABLED = process.env.OBSIDIAN_ENABLED === "true";
const STOCK_RADAR_SUBDIR = "StocksScalper";
const MAX_RETRIES = 3;
const BATCH_SIZE = 20;

interface JournalExportRow {
  id: string;
  kind: string;
  entityId: string;
  bucket: string;
  accountId: string | null;
  relativePath: string;
  contentHash: string;
  status: string;
  attempts: number;
  lastError: string | null;
}

/**
 * Render a markdown note for a given JournalExport row.
 * Fetches the entity data and formats it as structured Markdown.
 */
const renderNote = async (row: JournalExportRow): Promise<string> => {
  const now = new Date().toISOString();

  switch (row.kind) {
    case "TRADE_NOTE": {
      const pos = await prisma.position.findUnique({
        where: { id: row.entityId },
        include: {
          symbol: true,
          account: true,
          aiReviews: {
            where: { kind: { in: ["PRE_TRADE_CRITIC", "POST_TRADE_JOURNAL"] as any } },
            orderBy: { createdAt: "desc" },
            take: 2,
          },
        },
      }) as any;
      if (!pos) throw new Error(`Position ${row.entityId} not found`);

      const preReview = pos.aiReviews?.find((r: any) => r.kind === "PRE_TRADE_CRITIC");
      const postReview = pos.aiReviews?.find((r: any) => r.kind === "POST_TRADE_JOURNAL");

      const pnlSign = pos.realizedPnl >= 0 ? "+" : "";
      const duration = pos.closedAt && pos.openedAt
        ? Math.floor((new Date(pos.closedAt).getTime() - new Date(pos.openedAt).getTime()) / 60_000)
        : 0;

      return [
        `---`,
        `title: "${pos.symbol?.ticker} ${pos.direction} Trade"`,
        `date: ${pos.closedAt?.toISOString().split("T")[0] ?? now.split("T")[0]}`,
        `symbol: ${pos.symbol?.ticker}`,
        `direction: ${pos.direction}`,
        `pnl: ${pnlSign}${pos.realizedPnl?.toFixed(2) ?? "0.00"}`,
        `status: closed`,
        `account: ${pos.account?.label ?? "unknown"}`,
        `tags: [trade, ${pos.symbol?.ticker?.toLowerCase()}, ${pos.direction?.toLowerCase()}]`,
        `---`,
        ``,
        `# ${pos.symbol?.ticker} ${pos.direction} — ${pnlSign}${pos.realizedPnl?.toFixed(2)} USD`,
        ``,
        `**Account:** ${pos.account?.label ?? "unknown"}  `,
        `**Open:** ${pos.openedAt?.toISOString() ?? "—"}  `,
        `**Close:** ${pos.closedAt?.toISOString() ?? "—"}  `,
        `**Duration:** ${duration} min  `,
        `**Entry:** ${pos.avgEntryPrice?.toFixed(5)}  `,
        `**Stop:** ${pos.stopLoss?.toFixed(5)}  `,
        `**Take Profit:** ${pos.takeProfit?.toFixed(5)}  `,
        `**Size:** ${pos.quantity} lots  `,
        `**Realized PnL:** ${pnlSign}${pos.realizedPnl?.toFixed(2)} USD`,
        ``,
        preReview ? [
          `## Pre-Trade AI Review`,
          `**Verdict:** ${preReview.verdict}  `,
          `**Summary:** ${preReview.summary}`,
          preReview.concerns?.length ? `**Concerns:**\n${preReview.concerns.map((c: string) => `- ${c}`).join("\n")}` : "",
        ].filter(Boolean).join("\n") : "",
        postReview ? [
          ``,
          `## Post-Trade Debrief`,
          `${postReview.summary}`,
          ``,
          `**What went well:**`,
          ...(postReview.suggestions ?? []).map((s: string) => `- ${s}`),
          ``,
          `**What went poorly:**`,
          ...(postReview.concerns ?? []).map((c: string) => `- ${c}`),
        ].join("\n") : "",
        ``,
        `---`,
        `*Generated by StocksScalper on ${now}*`,
      ].filter(Boolean).join("\n");
    }

    case "WEEKLY_REVIEW": {
      const review = await (prisma as any).weeklyReview.findFirst({
        where: { accountId: row.accountId, weekStart: row.entityId.split("-").slice(-3).join("-") },
        include: { account: true },
      }).catch(() => null);

      const output = (review?.output ?? {}) as any;
      return [
        `---`,
        `title: "Week of ${review?.weekStart ?? "?"}"`,
        `weekStart: ${review?.weekStart ?? "?"}`,
        `account: ${review?.account?.label ?? "portfolio"}`,
        `tags: [weekly-review]`,
        `---`,
        ``,
        `# Weekly Review — ${review?.account?.label ?? "Portfolio"} — ${review?.weekStart ?? "?"}`,
        ``,
        `## Summary`,
        `${output.summary ?? "No summary."}`,
        ``,
        `## Top Wins`,
        ...(output.topWins ?? []).map((w: string) => `- ${w}`),
        ``,
        `## Top Losses`,
        ...(output.topLosses ?? []).map((l: string) => `- ${l}`),
        ``,
        `## Repeating Mistakes`,
        ...(output.repeatingMistakes ?? []).map((m: string) => `- ${m}`),
        ``,
        `## Next Week Recommendations`,
        ...(output.recommendations ?? []).map((r: string) => `- ${r}`),
        ``,
        `---`,
        `*Generated by StocksScalper on ${now}*`,
      ].join("\n");
    }

    default:
      return `# ${row.kind} Export\n\nEntityId: ${row.entityId}\nGenerated: ${now}\n`;
  }
};

/**
 * Safely resolve a file path within the vault — prevents path traversal.
 */
const safeVaultPath = (vaultRoot: string, relativePath: string): string => {
  const resolved = resolve(join(vaultRoot, STOCK_RADAR_SUBDIR, relativePath));
  const root = resolve(join(vaultRoot, STOCK_RADAR_SUBDIR));
  if (!resolved.startsWith(root + "/") && resolved !== root) {
    throw new Error(`Path traversal detected: ${relativePath}`);
  }
  return resolved;
};

export const runJournalExportSweeper = async (): Promise<void> => {
  if (!OBSIDIAN_ENABLED) {
    logger.debug("Journal export sweeper skipped — OBSIDIAN_ENABLED != true");
    return;
  }

  if (!VAULT_PATH) {
    logger.debug("Journal export sweeper skipped — OBSIDIAN_VAULT_PATH not set");
    return;
  }

  const pending = await (prisma as any).journalExport.findMany({
    where: {
      status: { in: ["PENDING", "FAILED"] },
      attempts: { lt: MAX_RETRIES },
    },
    orderBy: { updatedAt: "asc" },
    take: BATCH_SIZE,
  }) as JournalExportRow[];

  if (pending.length === 0) return;

  logger.info("Journal export sweep started", { count: pending.length });
  let written = 0;
  let skipped = 0;
  let failed = 0;

  for (const row of pending) {
    try {
      const absPath = safeVaultPath(VAULT_PATH, row.relativePath);
      const absDir = dirname(absPath);

      const content = await renderNote(row);
      const contentHash = createHash("sha256").update(content).digest("hex");

      // Skip if file exists and content unchanged
      if (existsSync(absPath)) {
        try {
          const existing = await readFile(absPath, "utf8");
          const existingHash = createHash("sha256").update(existing).digest("hex");
          if (existingHash === contentHash) {
            await (prisma as any).journalExport.update({
              where: { id: row.id },
              data: { status: "WRITTEN", contentHash, writtenAt: new Date() },
            });
            skipped++;
            continue;
          }
        } catch { /* will overwrite */ }
      }

      // Atomic write: write to .tmp, then rename
      await mkdir(absDir, { recursive: true });
      const tmpPath = `${absPath}.tmp`;
      await writeFile(tmpPath, content, "utf8");
      await rename(tmpPath, absPath);

      await (prisma as any).journalExport.update({
        where: { id: row.id },
        data: {
          status: "WRITTEN",
          contentHash,
          writtenAt: new Date(),
          attempts: row.attempts + 1,
          lastError: null,
        },
      });

      written++;
      logger.debug("Journal file written", { path: row.relativePath });
    } catch (err) {
      const error = (err as Error).message;
      await (prisma as any).journalExport.update({
        where: { id: row.id },
        data: {
          status: row.attempts + 1 >= MAX_RETRIES ? "FAILED" : "PENDING",
          attempts: row.attempts + 1,
          lastAttemptAt: new Date(),
          lastError: error,
        },
      });
      failed++;
      logger.warn("Journal export failed", { entityId: row.entityId, kind: row.kind, error });
    }
  }

  logger.info("Journal export sweep complete", { written, skipped, failed });
};
