/**
 * Stable codes for rule/account events, consumed by UI, logs, and AI
 * prompts. Keep these as string literals — they are part of the
 * external contract.
 */
export const ACCOUNT_RULE_CODES = {
  // Account state
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_BREACHED: "ACCOUNT_BREACHED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_WRONG_PHASE: "ACCOUNT_WRONG_PHASE",
  ACCOUNT_WRONG_KIND: "ACCOUNT_WRONG_KIND",
  ACCOUNT_KILL_SWITCH: "ACCOUNT_KILL_SWITCH",
  ACCOUNT_MODE_LOCKED: "ACCOUNT_MODE_LOCKED",
  ACCOUNT_BRIDGE_STALE: "ACCOUNT_BRIDGE_STALE",

  // Drawdown
  ACCOUNT_DAILY_DD_NEAR: "ACCOUNT_DAILY_DD_NEAR",
  ACCOUNT_DAILY_DD_BREACH: "ACCOUNT_DAILY_DD_BREACH",
  ACCOUNT_TOTAL_DD_NEAR: "ACCOUNT_TOTAL_DD_NEAR",
  ACCOUNT_TOTAL_DD_BREACH: "ACCOUNT_TOTAL_DD_BREACH",
  ACCOUNT_TRAILING_DD_BREACH: "ACCOUNT_TRAILING_DD_BREACH",

  // Per-trade caps
  ACCOUNT_RISK_TOO_HIGH: "ACCOUNT_RISK_TOO_HIGH",
  ACCOUNT_RR_TOO_LOW: "ACCOUNT_RR_TOO_LOW",

  // Portfolio caps
  ACCOUNT_MAX_POSITIONS: "ACCOUNT_MAX_POSITIONS",
  ACCOUNT_CORRELATION_CAP: "ACCOUNT_CORRELATION_CAP",
  ACCOUNT_CONCURRENT_RISK_CAP: "ACCOUNT_CONCURRENT_RISK_CAP",
  ACCOUNT_DUPLICATE_POSITION: "ACCOUNT_DUPLICATE_POSITION",
  ACCOUNT_HEDGE_FORBIDDEN: "ACCOUNT_HEDGE_FORBIDDEN",

  // Instrument / session
  ACCOUNT_ASSET_CLASS_FORBIDDEN: "ACCOUNT_ASSET_CLASS_FORBIDDEN",
  ACCOUNT_SYMBOL_FORBIDDEN: "ACCOUNT_SYMBOL_FORBIDDEN",
  ACCOUNT_SESSION_FORBIDDEN: "ACCOUNT_SESSION_FORBIDDEN",
  ACCOUNT_TIMEFRAME_FORBIDDEN: "ACCOUNT_TIMEFRAME_FORBIDDEN",
  ACCOUNT_TIME_WINDOW_FORBIDDEN: "ACCOUNT_TIME_WINDOW_FORBIDDEN",

  // News
  ACCOUNT_NEWS_BLACKOUT: "ACCOUNT_NEWS_BLACKOUT",

  // Payouts
  ACCOUNT_PAYOUT_PROTECT_ACTIVE: "ACCOUNT_PAYOUT_PROTECT_ACTIVE",

  // Weekend
  ACCOUNT_WEEKEND_HOLD_FORBIDDEN: "ACCOUNT_WEEKEND_HOLD_FORBIDDEN",

  // Generic allocator
  ACCOUNT_POLICY_MISMATCH: "ACCOUNT_POLICY_MISMATCH",
  ACCOUNT_SETUP_TAG_MISMATCH: "ACCOUNT_SETUP_TAG_MISMATCH",
  ACCOUNT_POLICY_LIMIT_REACHED: "ACCOUNT_POLICY_LIMIT_REACHED",
  ACCOUNT_SELECTED: "ACCOUNT_SELECTED",
  ACCOUNT_ELIGIBLE: "ACCOUNT_ELIGIBLE",
} as const;

export type AccountRuleCode = keyof typeof ACCOUNT_RULE_CODES;
