"use client";

import useSWR from "swr";
import { MetricCard, Panel, ScreenHeader, StatusPill } from "../components/screen";
import { fetcher, formatDateTime, formatMoney, formatPercent } from "../lib/api";

interface DashboardData {
  account: {
    balance: number;
    equity: number;
    freeMargin: number;
    openPnl: number;
    realizedPnlDaily: number;
    drawdownPct: number;
    riskState: string;
    killSwitchActive: boolean;
  } | null;
  activeTrades: number;
  recentActions: Array<{ message: string; createdAt: string; severity: string; category: string }>;
  riskWarnings: Array<{ id: string; eventType: string; message: string; severity: string; createdAt: string; blocking: boolean }>;
  workerHealth: Array<{ workerType: string; status: string; currentTask: string | null; lastSeenAt: string }>;
  killSwitchActive: boolean;
}

export default function DashboardPage() {
  const { data } = useSWR<DashboardData>("/api/dashboard/summary", fetcher, { refreshInterval: 5000 });

  return (
    <>
      <ScreenHeader
        eyebrow="Control Tower"
        title="Trading intelligence command center"
        description="Monitor account state, worker health, risk pressure, and the latest platform actions from one place."
      />

      <div className="metrics-grid">
        <MetricCard label="Balance" value={formatMoney(data?.account?.balance)} />
        <MetricCard label="Equity" value={formatMoney(data?.account?.equity)} tone={(data?.account?.openPnl ?? 0) >= 0 ? "good" : "warn"} />
        <MetricCard label="Free Margin" value={formatMoney(data?.account?.freeMargin)} />
        <MetricCard label="Open PnL" value={formatMoney(data?.account?.openPnl)} tone={(data?.account?.openPnl ?? 0) >= 0 ? "good" : "warn"} />
        <MetricCard label="Realized Today" value={formatMoney(data?.account?.realizedPnlDaily)} tone={(data?.account?.realizedPnlDaily ?? 0) >= 0 ? "good" : "warn"} />
        <MetricCard label="Drawdown" value={formatPercent(data?.account?.drawdownPct)} tone={(data?.account?.drawdownPct ?? 0) >= 2 ? "warn" : "default"} />
        <MetricCard label="Active Trades" value={data?.activeTrades ?? 0} />
        <MetricCard label="Kill Switch" value={data?.killSwitchActive ? "Active" : "Clear"} tone={data?.killSwitchActive ? "critical" : "good"} />
      </div>

      <div className="panel-grid">
        <Panel title="Worker Health" subtitle="Heartbeat and task visibility across the autonomous worker fleet.">
          <table className="data-table">
            <thead>
              <tr>
                <th>Worker</th>
                <th>Status</th>
                <th>Task</th>
                <th>Last Seen</th>
              </tr>
            </thead>
            <tbody>
              {(data?.workerHealth ?? []).map((worker) => (
                <tr key={worker.workerType}>
                  <td>{worker.workerType}</td>
                  <td><StatusPill value={worker.status} /></td>
                  <td>{worker.currentTask ?? "idle"}</td>
                  <td>{formatDateTime(worker.lastSeenAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Panel>

        <Panel title="Risk Warnings" subtitle="Blocking or cautionary events generated by the execution and supervisor layers.">
          <div className="list-stack">
            {(data?.riskWarnings ?? []).map((warning) => (
              <div className="list-item" key={warning.id}>
                <StatusPill value={warning.severity} />
                <p>{warning.message}</p>
                <small>{formatDateTime(warning.createdAt)}</small>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <Panel title="Recent Platform Actions" subtitle="Latest audit trail entries from workers, controls, and integrations.">
        <table className="data-table">
          <thead>
            <tr>
              <th>When</th>
              <th>Severity</th>
              <th>Category</th>
              <th>Message</th>
            </tr>
          </thead>
          <tbody>
            {(data?.recentActions ?? []).map((action, index) => (
              <tr key={`${action.createdAt}-${index}`}>
                <td>{formatDateTime(action.createdAt)}</td>
                <td><StatusPill value={action.severity} /></td>
                <td>{action.category}</td>
                <td>{action.message}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Panel>
    </>
  );
}
