FROM node:20-alpine

WORKDIR /app
COPY package.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/worker ./apps/worker

RUN npm install
RUN npm run prisma:generate -w packages/db
RUN npm run build -w packages/core -w packages/db -w apps/worker

CMD ["node", "apps/worker/dist/index.js"]
